version: '3.3'

services:
  kafka:
    image: 127.0.0.1:5001/db-adapter
    build: kafka-logstash-adapter/
    env_file:
      - .env
    ports:
      - "3030:3030"
    depends_on:
      - redis
    networks:
      - db-adapter
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 4G
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


  redis:
    image: redis:alpine
    networks:
      - db-adapter
    stop_grace_period: 1m30s
    deploy:
      placement:
        constraints: [node.role == manager]

# Network
networks:
  db-adapter:
