
FROM geodan/gost-db

USER root

# in the container you just started:
#ADD /var/lib/docker/volumes/compose_il08X_postgis/_data/ /var/lib/postgresql/data
RUN  chown -R postgres:postgres /var/lib/postgresql/data
USER postgres

